[build]
  publish = "public"
  command = "mkdir -p public && cp index.html public/ && cp students_import.json public/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "development" }
